// test/widget_test.dart
//
// The stock smoke test generated by `flutter create`. Automated
// testing isn't covered in this course — this file is left as
// generated so the project matches real `flutter create` output.
// The one change: it taps Icons.thumb_up instead of Icons.add,
// matching this session's fourth edit, so the project still runs
// end to end. You can ignore this file for now.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:first_app/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());

    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    await tester.tap(find.byIcon(Icons.thumb_up));
    await tester.pump();

    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
